# Site settings
title: 'Kevin Rockwood'
description: 'software developer'
url: 'http://rockwood.me'
baseurl: '/'
google_analytics: 'UA-24458949-2'
disqus_shortname: 'rockwood'

author:
  name: 'Kevin Rockwood'
  email: kevin@rockwood.me
  twitter_username: kevinrockwood
  github_username: rockwood
  linkedin_username: rockwood

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

sass:
  style: compressed

gems: ['jekyll-paginate']
exclude: ['vendor', 'README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
